# Generated by Django 5.0.4 on 2024-07-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0013_alter_shopitem_slug_alter_shopitem_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='examgenerator.question')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_question_text', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_question', to='examgenerator.question')),
            ],
            options={
                'verbose_name': 'Sub Question',
                'verbose_name_plural': 'Sub Questions',
            },
        ),
        migrations.CreateModel(
            name='SubAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_answer_text', models.TextField()),
                ('sub_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_answer', to='examgenerator.subquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.education_level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examgenerator.topic'),
        ),
    ]
