# Generated by Django 5.0.4 on 2024-07-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='examgenerator.question'),
        ),
    ]
