# Generated by Django 5.0.4 on 2024-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0003_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='answerimages/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questionimages/'),
        ),
        migrations.AddField(
            model_name='subanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subanswerimages/'),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subquestionimages/'),
        ),
    ]
