# Generated by Django 5.0.4 on 2024-07-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0004_answer_image_question_image_subanswer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='subsubquestionimages/')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_questions', to='examgenerator.subquestion')),
            ],
            options={
                'verbose_name': 'SubSub Question',
                'verbose_name_plural': 'SubSub Questions',
            },
        ),
        migrations.CreateModel(
            name='SubSubAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sub_answer_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='subsubanswerimages/')),
                ('sub_sub_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_answer', to='examgenerator.subsubquestion')),
            ],
        ),
    ]
