# Generated by Django 5.0.4 on 2024-07-05 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0005_subsubquestion_subsubanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subanswer',
            name='sub_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_answer', to='examgenerator.subquestion'),
        ),
    ]
