# Generated by Django 5.0.4 on 2024-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0008_question_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionsToExaminees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
