# Generated by Django 5.0.4 on 2024-07-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0009_instructionstoexaminees'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='marking_schemes/')),
                ('generated_exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_scheme', to='examgenerator.generatedexam')),
            ],
        ),
    ]
