# Generated by Django 5.0.4 on 2024-07-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0011_question_marks_subquestion_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='marks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subsubquestion',
            name='marks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
