# Generated by Django 5.0.4 on 2024-07-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0012_alter_question_marks_alter_subquestion_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexam',
            name='task_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
