# Generated by Django 5.0.4 on 2024-07-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0013_generatedexam_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexam',
            name='assessment_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
