# Generated by Django 5.0.4 on 2024-07-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0014_generatedexam_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexam',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
