# Generated by Django 5.0.4 on 2024-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0015_generatedexam_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGeneratorPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assignment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
