# Generated by Django 5.0.4 on 2024-07-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0016_examgeneratorprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexam',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
