# Generated by Django 5.0.4 on 2024-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplevelpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
