# Generated by Django 5.0.4 on 2024-05-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_toplevelpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplevelpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
