# Generated by Django 5.0.4 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
    ]
