# Generated by Django 5.0.4 on 2024-05-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
