# Generated by Django 5.0.4 on 2024-05-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
