# Generated by Django 5.0.4 on 2024-05-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, help_text='URL of the Facebook page', null=True)),
                ('telegram_url', models.URLField(blank=True, help_text='URL of the Telegram channel', null=True)),
                ('whatsapp_url', models.URLField(blank=True, help_text='URL of the WhatsApp group', null=True)),
            ],
        ),
    ]
