# Generated by Django 5.0.4 on 2024-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_socialmedialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='send_promotional_emails_to_all_users_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
