# Generated by Django 5.0.4 on 2024-05-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerfaq_vendorfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfaq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_images/'),
        ),
        migrations.AlterField(
            model_name='vendorfaq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_images/'),
        ),
    ]
