# Generated by Django 5.0.4 on 2025-01-01 16:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailschedule',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
