# Generated by Django 5.0.4 on 2025-01-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_emailschedule_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyPromotionEmail',
            new_name='PromotionEmailLog',
        ),
    ]
