# Generated by Django 5.0.4 on 2025-01-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_weeklypromotionemail_promotionemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionemaillog',
            name='email_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.emailschedule'),
        ),
    ]
