# Generated by Django 5.0.4 on 2025-01-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_promotionemaillog_email_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='emailschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
