# Generated by Django 5.0.4 on 2024-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='is_search_engine_indexible',
            field=models.BooleanField(default=False),
        ),
    ]
