# Generated by Django 5.0.4 on 2024-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='Aggregate_Rating_Value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='Best_Rating_Value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='Rating_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='Worst_Rating_Value',
            field=models.IntegerField(default=0),
        ),
    ]
