# Generated by Django 5.0.4 on 2024-05-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachments_sent',
            field=models.BooleanField(default=False),
        ),
    ]
