# Generated by Django 5.0.4 on 2024-05-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_attachments_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
