# Generated by Django 5.0.4 on 2024-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopitem_aggregate_rating_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shopitemimages/'),
        ),
    ]
