# Generated by Django 5.0.4 on 2024-05-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_transaction_item_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item_values',
        ),
    ]
