# Generated by Django 5.0.4 on 2024-05-22 08:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
