# Generated by Django 5.0.4 on 2024-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customer_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_item',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer_item',
            name='education_level',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer_item',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer_item',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
