# Generated by Django 5.0.4 on 2024-05-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_customer_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
