# Generated by Django 5.0.4 on 2024-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
