# Generated by Django 5.0.4 on 2024-05-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_customer_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_item',
            name='is_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
