# Generated by Django 5.0.4 on 2024-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customer_item_created_at_customer_item_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_item',
            name='is_created',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_items_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
