# Generated by Django 5.0.4 on 2024-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_customer_item_is_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='downloads_count',
            field=models.IntegerField(default=0),
        ),
    ]
