# Generated by Django 5.0.4 on 2024-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shopitem_downloads_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
