# Generated by Django 5.0.4 on 2024-07-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examgenerator', '0017_generatedexam_is_paid'),
        ('shop', '0013_alter_shopitem_slug_alter_shopitem_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generated_exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examgenerator.generatedexam'),
        ),
    ]
