# Generated by Django 5.0.4 on 2024-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_shopitem_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_item',
            name='file',
            field=models.FileField(upload_to='customer_items/'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='shopitemfiles/'),
        ),
    ]
