# Generated by Django 5.0.4 on 2024-09-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_generated_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MPESA', 'M-Pesa Express'), ('INTASEND', 'IntaSend')], max_length=20)),
            ],
        ),
    ]
