# Generated by Django 5.0.4 on 2024-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_paymentoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
