# Generated by Django 5.0.4 on 2024-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_paymentoption_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_delivered_to_all', models.BooleanField(default=False)),
            ],
        ),
    ]
