# Generated by Django 5.0.4 on 2024-10-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_shopitem_term_shopitem_term_level_shopitem_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='setbook_type_questions',
            field=models.CharField(blank=True, choices=[('Excerpt', 'Excerpt'), ('Essay', 'Essay'), ('General', 'General')], max_length=60, null=True),
        ),
    ]
