# Generated by Django 5.0.4 on 2024-05-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_order_created_at_vendorshop_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_order',
            name='display_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
