# Generated by Django 5.0.4 on 2024-05-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_order_display_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_order',
            name='vendor_is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
