# Generated by Django 5.0.4 on 2024-05-04 21:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_order_vendor_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorshop',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
