# Generated by Django 5.0.4 on 2024-05-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendorshop_available_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
