# Generated by Django 5.0.4 on 2024-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
