# Generated by Django 5.0.4 on 2024-05-05 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorcommission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcommission',
            name='value',
        ),
        migrations.AddField(
            model_name='vendorcommission',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
