# Generated by Django 5.0.4 on 2024-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_remove_vendorcommission_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorshop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
    ]
