# Generated by Django 5.0.4 on 2024-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_withdrawalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='beneficiary_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
