# Generated by Django 5.0.4 on 2024-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_withdrawalrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
