# Generated by Django 5.0.4 on 2024-05-07 11:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_withdrawalrequest_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorshop',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
