# Generated by Django 5.0.4 on 2024-05-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_productminprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productminprice',
            old_name='percentage',
            new_name='price',
        ),
    ]
